version: '3.7'

services:
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    environment:
    - MONGO_INITDB_DATABASE=heatmap-server
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=ChangeMe!
    volumes:
    - mongo-data:/data/db
    ports:
    - '27017:27017'

  mongo-ui:
    image: mongo-express:latest
    container_name: mongo-ui
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo-server
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=ChangeMe!
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=ChangeMe!
    ports:
    - '8081:8081'
    depends_on:
    - mongo-server

volumes:
  mongo-data: